# GraphQA Configuration File
# ===========================
# This file controls how GraphQA loads and processes datasets.
# Edit these settings to customize behavior for your needs.

# Dataset Configurations
datasets:
  conversation_analysis:
    name: "Conversation Analysis (REALTALK + WhatsApp)"
    description: "Multilingual conversation analysis with semantic metadata (26,907 messages)"
    loader_class: "ConversationAnalysisLoader"
    enabled: true
    config:
      # Path to ConvoKit corpus with Phase 2 metadata (absolute path)
      # Using forward slashes (works on Windows and Unix)
      corpus_path: "../conversation-analysis/data/processed/combined_bert"
      
      # No test mode needed - dataset is reasonable size (26K messages)
      # Loading takes ~10-30 seconds, ~200MB RAM
    
    # Expected data sources
    data_sources:
      - "../conversation-analysis/data/processed/combined_bert"


# Tool Configuration
tools:
  enabled: true
  max_results: 50
  cache_enabled: true
  performance_mode: "balanced"  # Options: fast, balanced, thorough

# LLM Configuration  
llm:
  # Model options:
  # - OpenAI: "gpt-4", "gpt-4o", "gpt-3.5-turbo"
  # - Google: "gemini-1.5-pro", "gemini-1.5-flash", "gemini-pro"
  model: "gemini-2.5-flash"
  temperature: 0.1
  max_tokens: 2000
  timeout_seconds: 40
  max_iterations: 15     # Agent reasoning steps before stopping (increased for relationship queries)

# Performance & Resource Limits
performance:
  max_graph_size: 100000      # Maximum nodes to prevent memory issues
  max_memory_mb: 2048         # Memory limit in MB
  parallel_processing: true   # Enable parallel processing where possible
  cache_directory: "data/cache"
  log_level: "INFO"           # DEBUG, INFO, WARNING, ERROR

# Quick Settings for Common Use Cases
# ====================================
# 
# 🚀 For DEMO/TESTING (current default):
#   amazon_products.config.test_mode: true
#   amazon_products.config.max_products: 5000
#   
# 🔥 For FULL ANALYSIS (requires more resources):  
#   amazon_products.config.test_mode: false
#   amazon_products.config.max_products: null
#   amazon_products.config.max_reviews: null
#
# ⚡ For CUSTOM LIMITS:
#   amazon_products.config.test_mode: false  
#   amazon_products.config.max_products: 25000  # Custom limit
#   amazon_products.config.max_reviews: 50000   # Custom limit 